version: '3'
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile.server
    image: server_image:latest
    environment:
      # read from .env file
      - HOST=${HOST}
      - PORT=${PORT}
    ports:
      # bind host 8080 port to container ${port}
      - "8080:${PORT}"
    networks:
      client-server:
    tty: true
networks:
  client-server:
    driver: bridge
